src/App.tsx
src/pages/LoginPage/index.tsx
src/pages/PaymentPage/paymentPage.tsx
src/pages/ShopPage/index.tsx
src/routes.tsx
src/styles/global.ts

Foi adicionado as rotas de todas as paginas 
foi adicionado todos os componentes default das paginas

feat:add all routes

---

src/components/Header/headerShop/headerShop.tsx

Foi atualizada a importação da imagem de logo do "header".

fix: import logo image

---

src/components/Header/headerSuccess/headerScuccess.tsx

Criado sub componente "successHeader"

feat: create success header

---

src/components/Form/PaymentForm/InputPayment/index.tsx
src/components/Form/PaymentForm/InputPayment/style.tsx
src/components/Form/PaymentForm/index.tsx
src/components/Form/PaymentForm/style.tsx
src/pages/PaymentPage/paymentPage.tsx
src/pages/PaymentPage/styles.ts

created paymentPage and PaymentForm , waiting for the item sum function and the header.

feat: Create PaymentPage and PaymentForm

---

src/components/Header/globalHeader/style.ts
src/components/Header/headerSuccess/headerScuccess.tsx
src/components/Header/headerSuccess/style.ts

Adicionado style para componente "headerSuccess"

style: add style to headerSuccess

---

index.html
src/components/Form/RegisterForm/registerForm.tsx
src/components/Form/RegisterForm/validations.tsx

Foi criadas as tags na pagina registerForm

feat: add registerPage

---

index.html

Noma da aplicação foi atualizada

fix: add title KNZ pet shop

---

src/components/CartModal/CartProductList/CartProductCard/cartProductCard.tsx
src/components/ProductList/ProductCard/productCard.tsx
src/pages/ShopPage/style.ts
src/provider/CartContext/CartContext.tsx

adicionando a persistência dos dados do carrinho no localStorage

feat:add localStorageCart function

---

src/components/Form/PaymentForm/InputPayment/index.tsx
src/components/Form/PaymentForm/InputPayment/style.tsx
src/components/Form/PaymentForm/index.tsx
src/components/Form/PaymentForm/style.tsx
src/components/Form/PaymentForm/validations.tsx
src/pages/PaymentPage/styles.ts
src/provider/UserContext/@Types.ts

create validations form payment and add react-hooks-form in paymentForm.

feat: create validations form payment and add hooks-form

---

src/components/Form/RegisterForm/registerForm.tsx
src/components/Form/RegisterForm/style.ts

Foi criado o botão de submit para formResgiter

feat: create buttom to formRegister if libary Material UI

---

src/components/Form/RegisterForm/style.ts

Foi criada a lógica para imagem aparecer no desktop e não aparecer no mobile

refactor: display image register form

---

src/components/Form/RegisterForm/style.ts

style: add font

---

src/components/Form/PaymentForm/index.tsx
src/components/Form/PaymentForm/style.tsx
src/pages/SucessPage/style.ts
src/pages/SucessPage/sucessPage.tsx

editei os estilos da PaymentPage e SucessPage, alterei os inputs do materialUI

fix : edit styled paymentPage and SucessPage

---

src/components/Background/backgroundDesk.tsx
src/components/Background/style.ts
src/components/Form/RegisterForm/registerForm.tsx

Foi criado a estilo de background para paginas

feat: create globa style backgrong

---

src/components/Form/LoginForm/index.tsx
src/components/Form/LoginForm/styledLoginForm.ts
src/pages/LoginPage/index.tsx
src/pages/LoginPage/style.ts

Adicinado style  e utlizado o button do material UI

refactor: add background and button material UI

---

package.json
src/components/Header/globalHeader/globalHeader.tsx
src/components/Header/globalHeader/style.ts
src/components/Header/headerShop/headerShop.tsx
src/components/Header/headerShop/styles.ts
src/components/Header/userHeader/style.ts
src/components/Header/userHeader/userHeader.tsx
src/pages/UserPage/userPage.tsx
yarn.lock

Os botões foram refatorados para padrão, utilizando a biblioteca Material UI.

refactor: buttons header to Material UI libary

---

src/components/Header/headerShop/headerShop.tsx
src/components/Header/headerShop/styles.ts
src/components/Header/userHeader/style.ts
src/components/Header/userHeader/userHeader.tsx

Adicionado style to buttons user page

Global header

---

src/components/Form/PaymentForm/index.tsx
src/components/Form/PaymentForm/style.ts

texto de informação das doações adicionada na pagina de pagamento. 
obs: git pull  realizado antes do commit

feat: add text info in donate from paymentpage

---

src/components/Form/Input/index.tsx
src/pages/ProfilePage/profilePage.tsx
src/pages/ProfilePage/style.ts

Adicionada modal de deletar conta.
Resolução de typescript para form.

feat: add modal delete

---

src/components/Header/userHeader/style.ts
src/components/Header/userHeader/userHeader.tsx

adicionando o menu responsivo no header da profilePage

feat: responsive header to profilePage

---

src/components/Background/BackgroundShop/backgroundShop.tsx
src/components/Background/BackgroundShop/style.ts
src/pages/ShopPage/shopPage.tsx

Foi criada a estilização global de background para as paginas de shop

feat: global background shop

---

src/pages/ProfilePage/style.ts

style: adjust mobile
